# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F8Lfgs2SW6KdZqGwkI_Wc4ykt5dRJ95X
"""

print("  ...Neslihan...")
for i in range(1, 10):
    print(' '* (9 - i) +  '☆'* (2 * i - 1))